PREFIX x2rm: <http://ids.unimaas.nl/rdf2xml/model/>
PREFIX d2s: <http://data2services/vocab/>
PREFIX ido: <http://identifiers.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX bioentity: <http://bioentity.io/vocab/>
CONSTRUCT 
{ 

    ### experimental-properties
    ?drugUri bioentity:filler [ a ?drugExpePropertiesType ;
        d2s:kind ?drugExpePropertiesKind ;
        d2s:value ?drugExpePropertiesValue ;
        d2s:source ?drugExpePropertiesSource ] .

    }
WHERE {
select * where { 
    # Get drug primary ID
    ?drugObj a x2rm:drugbank\/drug .
    ?drugObj x2rm:hasChild [ a x2rm:drugbank\/drug\/drugbank-id ; x2rm:hasAttribute [ a x2rm:drugbank\/drug\/drugbank-id\/\@primary ] ; x2rm:hasValue ?drugId ] .
    BIND ( iri(concat("http://identifiers.org/drugbank:", ?drugId)) AS ?drugUri )



    ### Get EXPERIMENTAL PROPERTIES
    ?drugObj x2rm:hasChild [ a x2rm:drugbank\/drug\/experimental-properties; 
        x2rm:hasChild [ a x2rm:drugbank\/drug\/experimental-properties\/property;
            x2rm:hasChild [ a x2rm:drugbank\/drug\/experimental-properties\/property\/kind; x2rm:hasValue ?drugExpePropertiesKind ] ;
            x2rm:hasChild [ a x2rm:drugbank\/drug\/experimental-properties\/property\/value; x2rm:hasValue ?drugExpePropertiesValue ] ;
            x2rm:hasChild [ a x2rm:drugbank\/drug\/experimental-properties\/property\/source; x2rm:hasValue ?drugExpePropertiesSource ]
     ] ] .
     BIND ( iri(concat("http://data2services/model/experimental-properties/", REPLACE(?drugExpePropertiesKind, " ", "", "i")) ) AS ?drugExpePropertiesType )
     # Generate type like: http://data2services/model/experimental-properties/MeltingPoint

}

}