INSERT {
  GRAPH <?_output> {
    ?Concept a <https://w3id.org/data2services/Concept> .
  }
} WHERE {
  SERVICE <?_service> {
    GRAPH <?_input> {
      SELECT * {
        [] a ?Concept .
      } LIMIT 10
    }
  }
}