PREFIX x2rm: <http://ids.unimaas.nl/rdf2xml/model/>
PREFIX d2s: <http://data2services/vocab/>
PREFIX ido: <http://identifiers.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX bioentity: <http://bioentity.io/vocab/>
CONSTRUCT 
{ 
    # external-identifiers
    ?drugUri bioentity:same_as ?drugIdentifierUri .
    ?drugIdentifierUri a bioentity:Drug .
    ?drugIdentifierUri bioentity:id ?drugIdentifierId .

    }
WHERE {
select * where { 
    # Get drug primary ID
    ?drugObj a x2rm:drugbank\/drug .
    ?drugObj x2rm:hasChild [ a x2rm:drugbank\/drug\/drugbank-id ; x2rm:hasAttribute [ a x2rm:drugbank\/drug\/drugbank-id\/\@primary ] ; x2rm:hasValue ?drugId ] .
    BIND ( iri(concat("http://identifiers.org/drugbank:", ?drugId)) AS ?drugUri )



    ### Get EXTERNAL IDENTIFIERS
    ?drugObj x2rm:hasChild [ a x2rm:drugbank\/drug\/external-identifiers; 
        x2rm:hasChild [ a x2rm:drugbank\/drug\/external-identifiers\/external-identifier;
            x2rm:hasChild [ a x2rm:drugbank\/drug\/external-identifiers\/external-identifier\/resource; x2rm:hasValue ?drugIdentifierResource ] ;
            x2rm:hasChild [ a x2rm:drugbank\/drug\/external-identifiers\/external-identifier\/identifier; x2rm:hasValue ?drugIdentifierId ]
     ] ] .
     BIND ( iri(concat("http://identifiers.org/", ENCODE_FOR_URI(REPLACE(?drugIdentifierResource, " ", "", "i")), ":", ?drugIdentifierId) ) AS ?drugIdentifierUri )

     # Build the external-identifier by removing all spaces and encode_for_uri



}

}