
name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    if: contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:

    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: umids/d2s-sparql-operations
        tag_with_ref: true
        # Use env var GITHUB_TAG (set auto from git repo)